version: "3.1"
services:
 db:
  container_name: demo-db
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: "mydb"
   MYSQL_ROOT_PASSWORD: "example"
  ports:
   - "3306:3306"
  volumes:
   - ./databases/data:/var/lib/mysql
   - ./databases/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
